branch-defaults:
  master:
    environment: MolekuleTraining-master-env
global:
  application_name: molekule-training
  default_ec2_keyname: e-vkuncbfzee
  default_platform: Node.js running on 64bit Amazon Linux/4.14.1
  default_region: us-east-1
